# 00 Introduction to Python basics

## Agenda 
- Setting up Python and Visual Studio Code
- Using Python in three ways (interactive, script, notebook)
- Build-in data types 
- Functions
- Concepts of object oriented programming
- Inheritance 
- Numpy


## Setting up Python
There are many ways to install Python and many editors to write Python code. If you have already a version of Python or Anaconda installed, you can keep that version. However, if you are installing Python for the first time, I recommend the following procedure:

### Install a minimal Python
- Go to https://github.com/conda-forge/miniforge and download installer of "Miniforge 3" for your operating system
- Start the installer
- Install for "Just Me" and add to PATH variable

### Install Visual Studio Code as your code editor
- Go to https://code.visualstudio.com and download installer of "Visual Studio Code" for your operating system 
- Start the installer
- Install using your personal preferences (desktop icon etc.)
- Customize to your liking


## Using Python in three ways
There are several ways to execute Python code. We take a look at three options and subsequently 

### Command prompt
This is a quick way to execute or test a few Python commands, but not for serious programming. 

Open a command promt (Windows Terminal) and type 
```
conda activate base
```
Then type 
```
python
```
and you are in an interactive python promt, where you can execute Python commands:
```
a = 5
print("My variable 'a' has the value:")
print(a)
```

### Execute a Python script
For longer scripts you can store your commands in a ".py" file, which is then executed in a terminal window.

Create a new file in VS Code named `test_script.py` and enter the example code: 
```
a = 5
print("My variable 'a' has the value:")
print(a)
```
On the bottom right of your VS Code Window, there should be a button to select a Python Interpreter. Set it to "'base': conda". 

Open a Terminal in VS Code (or somewhere else and navigate to your directory with the file) and activate your Python environment: 
```
conda activate base
```
Then type 
```
python test_script.py
```
to execute your script.

### Jupyter Notebooks
A very convenient and popular alternative for beginners are interactive Jupyter Notebooks. We will use such notebooks in this lecture series.

In VS Code, you may create a file `test_script.ipynb`. If you open that file, you can select the Kernel on the top right button "Select Kernel". Now you have a Notebook in which you can create Markdown cells for text (indeed, you are reading such a Markdown cell right now) and Python code cells to write Python code. The next cell is of such type - try running is with the Play button on the left of the cell or by hitting "SHIFT" and "ENTER" at the same time. 


In [1]:
a = 5
print("My variable 'a' has the value:")
print(a)

My variable 'a' has the value:
5


## Build-in data types 
### Primitive data types
Great, you have already executed your first lines of Python code! Let's take a look at what was going on here:

The line `a = 5` defines a new variable named `a` and assigns the value 5 to it. In contrast to many other programming languages, the type of this variable is assigned implicitly - in this case it is of the type `int` meaning integer. We can confirm this using the build-in `type()` function:

In [2]:
type_of_a = type(a)
print(type_of_a)

<class 'int'>


Another variable type is a character string (`str`) that is implicitly defined using quotation marks. This can be double quotes or single quotes, but I recommend double quotes. In addition, there is a special string character type called f-String in modern Python. It can be used to format results nicely. 

In [3]:
str_variable = "A character string"
another_str_variable = 'Another character string'

formatted_string = f"My variable 'a' has the value {a} and my variable 'str_variable' has the value '{str_variable}'."
print(formatted_string)

My variable 'a' has the value 5 and my variable 'str_variable' has the value 'A character string'.


The next line in the first example `print("My variable 'a' has the value:")` prints a charcter string using the build-in `print()` function. But there are more build-in data types than just integers an strings:

In [4]:
xf = 2.75 # float 
xc = 1+3j # complex
xb = True # bool
xn = None # NoneType

We can convert between types using the type name as a function. Often, this is done automatically, e.g. we can user print(a) instead of print(str(a)) and the result of `div = 5/2` is automatically 2.5. But we should be aware of the types we use, therefore I would recommend writing `div = 5.0/2.0`.

In [5]:
af = float(a)
type_of_af = type(af)
print(af)
print(type_of_af)

5.0
<class 'float'>


We can use these data types to calculate stuff just like in a calculator:

In [6]:
# Add numbers 
number1 = 12389849
number2 = 92849302487
print(number1 * number2)

1150388837569254463


In [7]:
# Evaluate boolean expressions
b1 = True
b2 = False 
b3 = True 
print (b1 and not (b2 or b3))

False


In [8]:
# Compute the area of a circle
PI = 3.1415926535
r = 5.0
area = PI * r **2
print(f"The area of a circle with radius {r} is {area:.2f}.")

The area of a circle with radius 5.0 is 78.54.


### Sequences

There are also data types to collect variables. A `list` stores ordered variables (of multiple types) dynamically, while a `tuple` contains ordered variables (of multiple types) immutably.

In [9]:
fruit_list = ["bananas", "apples", "peaches"]    # list
fruit_tuple = ("bananas", "apples", "peaches")    # tuple

We can traverse trough lists and tuples using a for loop. Everything that should happen inside the loop, must use indentation:

In [10]:
for fruit in fruit_list:
    print(fruit)

bananas
apples
peaches


We can change a list item, but not a tuple item

In [11]:
fruit_list[1] = "melons"
print(fruit_list)

['bananas', 'melons', 'peaches']


We can also append data to a list:

In [12]:
fruit_list.append("apples")
print(fruit_list)

['bananas', 'melons', 'peaches', 'apples']


### Dictionaries
Sometimes we want to store sequences as key, value pairs. For this, we can use dictionaries:

In [13]:
person = {"Name": "Joe", "Age": 80}

print(person["Name"])
print(person["Age"])

Joe
80


You may iterate conveniently through dictionaries like this:

In [14]:
for key, value in person.items():
    print(f"{key}: {value}")

Name: Joe
Age: 80



## Functions
A fundamental principal of writing code is "Don't repeat yourself" (DRY). This means that we want to write code for a functionality once and reuse it instead of copying chunks of code. Lets say, we want to compute the area of a circle more often, then we want to define a function once and just call that function instead of writing the same all over again.

A function starts with `def`, the name of the function `compute_circle_area`, arguments enclosed in brackets `(radius)` and a colon `:`. everything inside the function is indented:

In [15]:
def compute_circle_area(radius):
    # Compute the area for a circle with 'radius'
    PI = 3.1415926535
    area = PI * radius **2
    return area 


print(compute_circle_area(3.0))
print(compute_circle_area(5.0))

28.2743338815
78.5398163375


The function `compute_circle_area` takes one argument and returns one result. But there can be also functions without arguments or without a `return` statement:

In [16]:
def write_hello():
    # A function that writes a fixed phrase 
    print("I promise to use the DRY principle.")

for i in range(10):
    write_hello()

I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.
I promise to use the DRY principle.


Functions may also take multiple arguments, some of which can have default values

In [17]:
def compute_vector_norm(x, y, z=0):
    # Return the squared length of a vector defined by x,y,z
    return(x**2 + y**2 + z**2)**0.5

n = compute_vector_norm(1,2,3)
print(n)

n = compute_vector_norm(1,2)
print(n)

vec = [1,2,3]
n = compute_vector_norm(*vec)
print(n)

3.7416573867739413
2.23606797749979
3.7416573867739413


Function can also return lists and thus essentially return multiple values. We illustrate this by writing our first algorithm.

In [18]:
def find_max(input):
    # Compute maximum value and position of the maximum in and input list 
    # The result is returned as a list containing [maximum, idx]
    current_max = -1
    current_idx = -1
    for i, val in enumerate(input):
        if val > current_max:
            current_max = val
            current_idx = i
    return [current_max, current_idx]


random_numbers = [33, 43, 9, 7, 38, 25, 17, 19, 29]

# Use 
result = find_max(random_numbers)
print(f"Resulting list: {result}")

value, position = find_max(random_numbers)
print(f"Resulting value: {value}, resulting position: {position}")

value, _ = find_max(random_numbers)
print(f"Just the resulting value: {value}")



Resulting list: [43, 1]
Resulting value: 43, resulting position: 1
Just the resulting value: 43


## Concepts of object oriented programming
The primitive data types like floats, strings, lists and dictionaries are cool. However, they are a bit limited. It would be great if we could define more complex data types like points, users, microscopes, spaceships, or any other object. 

Luckliy we can do this using object oriented programming. The idea here is that we can improve the reusability of code by abstracting indvidual objects which can interact. New custom objects are created from a template called `class`. 

### Example: geometric objects
A point has spatial coordinates. A line is defined by two points and should have the functionality of computing its length.

Let's first define a class for points. The class is defined by the keyword `class`. It has a special funtion to initialize the class called `__init__`. This is called the constructor. It works like any other function, however class functions always take a first argument called `self`. This is a reference to the class itself. For the point, the contructor takes three arguments (`x`, `y`, `z`) in addition to `self` and saves them to the class itself. 

In [19]:
class Point: 
    def __init__(self, x, y, z):
        self.x = x 
        self.y = y
        self.z = z

Let's also create a class for a line. The constructor works just like the points constructor. In addition, this class should also get some more functionality, i.e. compute the length. Therefore we add a class function called `compute_length` that takes only `self` as an argument and returns the length of the line.

In [20]:
class Line: 
    def __init__(self, a, b):
        self.a = a
        self.b = b
    
    def compute_length(self):
        dx = self.a.x - self.b.x
        dy = self.a.y - self.b.y
        dz = self.a.z - self.b.z
        return (dx**2 + dy**2 + dz**2)**0.5

We can now use the class and create points (Note that the type of these points is now our new data type `Point`!):

In [21]:
a = Point(1.0, 2.0, 3.0)
b = Point(0.0, 1.0, 5.0)
c = Point(5.0, 2.0, -3.0)

print(type(a))

<class '__main__.Point'>


We can define lines between these points and compute their lengths 

In [22]:
a_b = Line(a, b)
a_c = Line(a, c)

print(a_b.compute_length())
print(a_c.compute_length())

2.449489742783178
7.211102550927978


The advantage of these objects is that they are quite easy to read, interpret, and adapt. 

### Example: cars on a street
Let's take a look at another example. We define a class `Car` to represent cars. A car will be represented by a symbol (e.g. "=" or "*"), has a speed and a brand name. It has a function `drive` that computes how far the car drives in a given time. 

In [23]:
class Car:
    def __init__(self, symbol, brand, speed):
        self.symbol = symbol
        self.brand = brand
        self.speed = speed
    
    def __str__(self):
        return self.brand
    
    def plot(self):
        return self.symbol
    
    def drive(self, time):
        return self.speed * time

We can create a couple of cars. 

In [24]:
multipla = Car("🚗", "Fiat", 1)
golf = Car("🚙", "VW", 2)
f40 = Car("🏎️", "Ferrari", 3)

Now, we need a street for the cars to drive on. 

In [25]:
class Street: 
    def __init__(self, length=100):
        self.cars = length*[None]

    def add_car(self, car, position):
        self.cars[position] = car

    def update(self, time):
        N = len(self.cars)
        new_cars = N*[None]

        # Drive all cars (does not account for crashes or street ends)
        for i, car in enumerate(self.cars):
            if car:
                new_position = (i - car.drive(time))
                new_cars[new_position] = car
        
        self.cars = new_cars

    def __str__(self):
        characters = "["
        for car in self.cars:
            if car:
                characters += car.plot()
            else: 
                characters +=  " "
        characters += "]"
        return characters

Now, we can put our little street model together

In [26]:
# Create a new Street
sesame_street = Street() 

print(sesame_street)

[                                                                                                    ]


In [27]:
# Add the cars 
sesame_street.add_car(multipla, 10)
sesame_street.add_car(golf, 55)
sesame_street.add_car(f40, 90)

print(sesame_street)

[          🚗                                            🚙                                  🏎️         ]


In [28]:
sesame_street.update(5)
print(sesame_street)

[     🚗                                       🚙                             🏎️                        ]


## Inheritance and polymorphism 

Inheritance allows us to derive special versions of classes that inherit properties and methods from their parent classes. To inherit a class form another class we use the syntax 
```
class MyNewClass(MyParentClass):
```
in the class defintion. 

For example, a Taxi is a very specific version of a car that shares the base functionality and properties with a car (like `brand`, `speed`,  `drive()`), but has some additional properies and fucntions (like `pick_up_customer`).

In [29]:
class Taxi(Car):
    def __init__(self, brand, speed):
        super().__init__("🚕", brand, speed)
        self.customer = None

    def pick_up_customer(self, customer_name):
        self.customer = customer_name

    def plot(self): 
        if self.customer:
            return self.symbol + f"({self.customer})"
        else: 
            return self.symbol

Let's create taxis.

In [30]:
taxi_a = Taxi("Mercedes", 2)
taxi_b = Taxi("Audi", 2)

sesame_street.add_car(taxi_a, 30)
sesame_street.add_car(taxi_b, 35)

print(sesame_street)

[     🚗                        🚕    🚕         🚙                             🏎️                        ]


In [31]:
taxi_a.pick_up_customer("NM")
sesame_street.update(3)

print(sesame_street)

[  🚗                     🚕(NM)    🚕         🚙                          🏎️                                 ]


## Numpy
Numpy is an important package for scientific computing. It provides powerful tools for arrays and numerical computations. We can load the numpy package with the `import` statement, for example `import numpy`. Whenever we want to use a numpy function or class, we may call it with `numpy.function_name()`. 

In [32]:
import numpy

### Numpy data types 
The core data type used in the previous example is `ndarray`, an array class for numpy.

In [33]:
a = numpy.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


We can verify the type and access some basic properties of the numpy array `a`:

In [34]:
print(type(a))  
print(a.ndim)   # Number of dimensions
print(a.shape)  # Shape of array
print(a.size)   # Total number of entries
print(a.dtype)  # Data type in the array

<class 'numpy.ndarray'>
2
(2, 3)
6
int64


We can create numpy arrays from lists with the `numpy.array()` function.

In [35]:
b = numpy.array([1,2,3])                    # Integer array
c = numpy.array([1,2,3], dtype=float)       # Float array
d = numpy.array([0.4, 0.5, 0.6, 0.9])       # Float array
e = numpy.array([[1.5, 2, 3], [4, 5, 6]])   # Two-dimensional array
print(b.dtype)
print(c.dtype)

int64
float64


We can also create placeholder values:

In [36]:
f = numpy.zeros((3,2))          # Array filled with zeros
g = numpy.ones((2,3))           # Array filled with ones
h = numpy.eye(3)                # Array filled with identity matrix
r = numpy.random.random((3,3))  # Array with random values

x = numpy.linspace(0,1,11)      # Array filled with evenly spaced values
y = numpy.arange(0,30,5)        # Array filled with evenly spaced values 
print(r)


[[0.75828045 0.46501888 0.95015722]
 [0.81510203 0.41341171 0.72714924]
 [0.72769222 0.14886762 0.44349259]]


### Indexing and slicing 
We can index and slice parts of numpy arrays:

In [37]:
print(f"Input array: {x}")
print("Outputs:")
print(x[3])         # The fourth(!) entry of 'x'
print(x[-2])        # The second last entry of 'x'
print(x[2:5])       # The entries 2-4 of 'x'
print(x[::3])       # Every third entry of 'x' 
print(x[::-1])      # Reversed order of 'x'
print(x[x>0.5])     # Select elements larger than 0.5
print(x[b])         # Index with another integer numpy array

print("Input array:")
print(r)
print("Outputs:")
print(r[1,1])       # The entry at the 1,1 position of 'r'
print(r[:,1])       # The second column of 'r'
print(r[0:2, 0:2])  # The top lefet corner entries of 'r'


Input array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Outputs:
0.30000000000000004
0.9
[0.2 0.3 0.4]
[0.  0.3 0.6 0.9]
[1.  0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0. ]
[0.6 0.7 0.8 0.9 1. ]
[0.1 0.2 0.3]
Input array:
[[0.75828045 0.46501888 0.95015722]
 [0.81510203 0.41341171 0.72714924]
 [0.72769222 0.14886762 0.44349259]]
Outputs:
0.4134117106791634
[0.46501888 0.41341171 0.14886762]
[[0.75828045 0.46501888]
 [0.81510203 0.41341171]]


### Reshaping
We can modify the shapes of arrays:

In [38]:
print(a.T)                  # Transpose an array
print(a.ravel())            # Flatten the array to one dimension
print(d.reshape((2,2)))     # Reshape an array
print(numpy.vstack([b,b]))  # Stack arrays vertically
print(numpy.hstack([b,b]))  # Stack arrays horizontally

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[0.4 0.5]
 [0.6 0.9]]
[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]


### Pointwise mathematical operations
We can also do all kind of maths with numpy arrays:

In [39]:
print("Input arrays")
print(f"b: {b}")
print(f"c: {c}")

print("Outputs")
print(b+c)              # Pointwise addition
print(b-c)              # Pointwise difference
print(b/c)              # Pointwise division
print(b*c)              # Pointwise multiplication
squared = x**2          # Pointwise power
sine = numpy.sin(x)     # Pointwise sine
exp = numpy.exp(x)      # Pointwise exponential

Input arrays
b: [1 2 3]
c: [1. 2. 3.]
Outputs
[2. 4. 6.]
[0. 0. 0.]
[1. 1. 1.]
[1. 4. 9.]


### Matrix multiplication example
To demonstrate the power of numpy, we take a look at the matrix product. The product between a Matrix $A \in \reals^{n \times m}$ and another matrix $ B \in \reals^{m \times o}$ is 
$$
    C = A B,  
$$
with $C \in \reals^{n \times o}$
It is computed as 
$$
    C_{ij} = \sum_{k} A_{ik} B_{kj}
$$

In [40]:
m = 1000
n = 100
o = 500

A = numpy.random.random((n,m))
B = numpy.random.random((m,o))
C = numpy.zeros((n,o))

A naive implementation of the matrix product looks like this:

In [41]:
for i in range(n):
    for j in range(o):
        for k in range(m):
            C[i,j] += A[i,k] * B[k,j]

The expression above is very slow, as the Python intepreter does not apply any optimization or vectorization for the processor to be fast. The same code using numpy looks like this: 

In [42]:
C = numpy.matmul(A, B)

This code executed way faster, because the underlying implementation is pre-compiled and optimized for your processor. Whenever there is a precompiled version of a function that saves a lot of lopping in Python, use that version! Looping in Python is relatively slow.

The matrix multiplication is so common, that there is a dedicated operator for it: 

In [43]:
C = A @ B